export const languages = [
    {
        id: 1,
        language: "Türkçe",
        value: "turkce",
        about: "Hakkımda",
        projects: "Projeler",
        contact: "İletişim",
        quote1: "Başarı, her gün tekrarlanan küçük çabaların toplamıdır.",
        quote2: "Azim, başarısızlıktan yılmamak ve her seferinde daha güçlü bir şekilde geri dönmektir.",
        quote3: "Hayallerinizi gerçekleştirmek için gereken azmi gösterirseniz, hiçbir engel sizi durduramaz.",
        quote4: "Çalışmak, umutla birleştiğinde mucizeler yaratır.",
        quote5: "Azimle çalışmanın en büyük ödülü, hayallerinizin gerçeğe dönüşmesidir.",
        hire: "Anlaş",
        cv: "CV İndir",
        users: "Kullanıcılar",
        awards: "Başarılar",
        years: "Tecrübe (Yıl)",
        aboutMe: "Zonguldak Bülent Ecevit Üniversitesi'nden mezun bir yazılım geliştiricisiyim. Next.js, TypeScript, " +
            "JavaScript ve React konularında geniş bir bilgiye sahibim. Teknolojik yenilikleri takip ederek, etkili ve " +
            "kullanıcı dostu çözümler üretmeye odaklanıyorum. Projelerde kaliteli ve verimli sonuçlar elde etmek için " +
            "sürekli öğrenme ve gelişmeye önem veriyorum.",
        skills: "Yetenekler",
        education: "Eğitim",
        certifications: "Sertifikalar",
        noneCertificate: "Sertifika bulunamadı !",
        university: "Üniversitesi",
        myProjects: "Projelerim",
        all: "Hepsi",
        letsConnect: 'İletişime Geçelim',
        // letsConnect: 'Haydi İletişime Geçelim',
        letsConnectDesc: "Sizinle tanışmak ve projeleriniz hakkında konuşmak benim için büyük " +
            "bir zevk olacak. Sorularınız, işbirliği teklifleriniz ya da " +
            "teknoloji üzerine sohbet etmek isterseniz, aşağıdaki iletişim " +
            "seçenekleri aracılığıyla bana ulaşabilirsiniz. Birlikte neler " +
            "yapabileceğimizi keşfetmek için sabırsızlanıyorum. İletişime " +
            "geçmekten çekinmeyin!",
        yourEmail: "Mail Adresin",
        yourEmailPlaceholder: "Mail",
        subject: "Konu",
        message: "Mesajınız",
        messagePlaceholder: "Mesajınızı buraya yazın.",
        sendMessage: "Mesajı Gönder",
        allRights: "Tüm hakları saklıdır.",
        headsUp: "Mesaj gönderimi başarılı!",
        headsUpMessage: "Mesajınız başarıyla tarafıma iletilmiştir. Size en kısa zamanda dönüş yapacağım.",
        coffeProjectDesc: "Tek sayfalık bu kahve sitesi, kullanıcı dostu tasarımıyla kahve severler için bilgi ve seçenekler sunar.",
        coffeProjectTitle: "Kahve Websitesi",
        saasProjectDesc: "Bu landing page, ürününüzü etkili bir şekilde tanıtarak ziyaretçileri çekmeyi ve satışları artırmayı hedefler.",
        saasProjectTitle: 'SAAS',
        eCommerceProjectDesc: "Bu e-ticaret projesi, modern arayüzü, doğrulama işlemleri ve kullanıcı dostu özellikleri ile online alışveriş deneyimini optimize eder.",
        eCommerceProjectTitle: 'E-Ticaret NextJS',
        netflixProjectDesc: "Bu proje, şık ve kullanıcı dostu arayüzü ile Netflix benzeri bir akış platformu deneyimi sunar, film ve dizileri keyifle izlemeyi sağlar.",
        netflixProjectTitle: "Netflix Klon",
        dijirackProjectDesc: 'Bu monitoring sistemi, ağ ve sistem performansını gerçek zamanlı izleyerek sorunları hızlıca tespit ve çözüm sunar.',
        dijirackProjectTitle: 'Dijirack İzleme',
        ifiProjectDesc: 'Bu proje, atık toplama süreçlerini optimize ederek verimli planlama ve yönetim sağlar.',
        ifiProjectTitle: 'IFI Atık Toplama',
        medScriptProjectDesc: 'Bu proje, ilaçların birbirleriyle olan potansiyel yan etkileşimlerini analiz ederek güvenli bir kullanım sağlar.',
        medScriptProjectTitle: 'Medscript',
        anonymous: 'Anonim',
    },
    {
        id: 2,
        language: "English",
        value: "english",
        about: "About",
        projects: "Projects",
        contact: "Contact",
        quote1: "Success is the sum of small efforts repeated day in and day out.",
        quote2: "Determination is not being discouraged by failure and coming back stronger every time.",
        quote3: "If you show the determination needed to achieve your dreams, no obstacle can stop you.",
        quote4: "Working combined with hope creates miracles.",
        quote5: "The greatest reward of working with determination is the realization of your dreams.",
        hire: "Hire",
        cv: "Download CV",
        users: "Users",
        awards: "Awards",
        years: "Experience (Years)",
        aboutMe: "I am a software developer with " +
            "a degree from Zonguldak Bülent Ecevit University. I have extensive " +
            "knowledge in Next.js, TypeScript, JavaScript, and React. I focus on " +
            "producing effective and user-friendly solutions by keeping up with " +
            "technological innovations. I emphasize continuous learning and " +
            "development to achieve high-quality and efficient results in projects.",
        skills: "Skills",
        education: "Education",
        certifications: "Certifications",
        noneCertificate: "Not found certificate !",
        university: "University",
        myProjects: "My Projects",
        all: "All",
        letsConnect: 'Let\'s Connect',
        letsConnectDesc: 'I would be delighted to connect with you and ' +
            'discuss your projects. If you have any questions, collaboration ' +
            'proposals, or simply want to chat about technology, feel free to ' +
            'reach out through the contact options below. I\'m excited to explore ' +
            'what we can achieve together. Don\'t hesitate to get in touch!',
        yourEmail: "Your Email",
        yourEmailPlaceholder: "Email",
        subject: "Subject",
        message: "Message",
        messagePlaceholder: "Type your message here.",
        sendMessage: "Send Message",
        allRights: "All rights reserved.",
        headsUp: "Message sending successful!",
        headsUpMessage: "Your message has been successfully sent to me. I will get back to you as soon as possible.",
        coffeProjectDesc: "This single-page coffee site offers information and options for coffee enthusiasts with its user-friendly design.",
        coffeProjectTitle: "Coffe Website",
        saasProjectDesc: "This landing page aims to attract visitors and increase sales by effectively showcasing your product.",
        saasProjectTitle: 'SAAS',
        eCommerceProjectDesc: "This e-commerce project optimizes the online shopping experience with its modern interface, validation processes, and user-friendly features.",
        eCommerceProjectTitle: 'Ecommerce NextJS',
        netflixProjectDesc: "This project provides a Netflix-like streaming platform experience with its sleek and user-friendly interface, allowing users to enjoy movies and TV shows.",
        netflixProjectTitle: "Netflix Clone",
        dijirackProjectDesc: 'This monitoring system provides real-time network and system performance tracking, quickly identifying and resolving issues.',
        dijirackProjectTitle: 'Dijirack Monitoring',
        ifiProjectDesc: 'This project optimizes waste collection processes, providing efficient planning and management.',
        ifiProjectTitle: 'IFI Waste Collection',
        medScriptProjectDesc: 'This project analyzes potential interactions between medications, ensuring safe usage.',
        medScriptProjectTitle: 'Medscript',
        anonymous: 'Anonymous',
    },
]